#!/bin/bash
# Simple deployment script for RPE Dashboard

echo "🚀 CofC Soccer RPE Dashboard - Deployment Options"
echo "================================================"
echo ""
echo "CURRENT STATUS:"
echo "✅ Web app running locally at: http://localhost:5000"
echo "✅ Network access at: http://$(ipconfig getifaddr en0):5000"
echo ""
echo "SHARING OPTIONS:"
echo ""
echo "1. 📱 SAME WIFI (Easiest)"
echo "   - Share this URL with coaches: http://$(ipconfig getifaddr en0):5000"
echo "   - Works when they're on same WiFi as you"
echo ""
echo "2. 🌐 INTERNET ACCESS (Best for remote coaches)"
echo "   - Use ngrok for instant public URL:"
echo "   - brew install ngrok"
echo "   - ngrok http 5000"
echo "   - Share the ngrok URL (e.g., https://abc123.ngrok.io)"
echo ""
echo "3. ☁️ CLOUD DEPLOYMENT (Most professional)"
echo "   - Deploy to Heroku, Railway, or Render"
echo "   - Available 24/7 from anywhere"
echo ""
echo "QUICK START FOR COACHES:"
echo "========================"
echo "1. Open browser on phone/computer"
echo "2. Go to: http://$(ipconfig getifaddr en0):5000"
echo "3. Bookmark the page"
echo "4. Click 'Refresh Dashboard' for latest data"
echo ""
echo "Press Ctrl+C in the terminal running the app to stop it."
