name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports and basic functionality
      run: |
        python -c "import app; print('✅ App imports successfully')"
        python -c "import pandas, matplotlib, seaborn, flask; print('✅ All dependencies available')"
    
    - name: Check code syntax
      run: |
        python -m py_compile app.py
        python -m py_compile rpe.py
        echo "✅ Python syntax check passed"
    
    - name: Verify deployment files
      run: |
        test -f Procfile && echo "✅ Procfile exists"
        test -f runtime.txt && echo "✅ Runtime.txt exists"
        test -f requirements.txt && echo "✅ Requirements.txt exists"
        test -f templates/dashboard.html && echo "✅ Template exists"
        echo "✅ All deployment files present"
